# Generated by Django 6.0.3 on 2026-03-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('reservation_interval', models.PositiveIntegerField(default=30)),
                ('reservation_duration', models.PositiveIntegerField(default=90)),
            ],
            options={
                'verbose_name': 'Configuración del restaurante',
                'verbose_name_plural': 'Configuración del restaurante',
            },
        ),
    ]
